service: stock-pool # NOTE: update this with your service name

plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 128
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    ACCOUNT_ID: 977250694392
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  create:
    handler: stocks/create.create
    events:
      - http:
          path: stocks
          method: post
          cors: true

  list:
    handler: stocks/list.list
    events:
      - http:
          path: stocks
          method: get
          cors: true

  get:
    handler: stocks/get.get
    events:
      - http:
          path: stocks/{id}
          method: get
          cors: true

  update:
    handler: stocks/update.update
    events:
      - http:
          path: stocks/{id}
          method: put
          cors: true

  remove:
    handler: stocks/remove.remove
    events:
      - http:
          path: stocks/{id}
          method: delete
          cors: true

resources:
  Resources:
    StocksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}